### ISSUE TITLE
Release V 3.1

### ISSUE THREAD

**Issue by mpostol** [mpostol/UA-ModelCompiler#91]
# Tasks

- [x] Draft new release front page
- [x] Create milestone to resolve all outstanding issues
- [x] Update version information for all published assemblies
- [x] Prepare an example if applicable
- [x] Update the Readme file
- [x] Prepare and publish NuGet packages if applicable 
- [x] Create release front page
  - [x] Version information
    - [x] Changes
  - [x] Getting Started (ASMD)
  - [x] [How to follow up? (gist)](https://gist.github.com/mpostol/0692302e1b93eb55e9862219c2c58f12)
  - [x] [How to Install (gist)](https://gist.github.com/mpostol/6b731a25b65e5379a925c3592550c8fe)
- [x] Build solution to create deliverable and publish the installation package
- [x] Update and publish the code help documentation
- [x] Publish release
- [x] Update the README.md
- [x] Update the GitHub pages documentation
- [x] Close this issue and the parent milestone

**Comment by mpostol** [comment]
## Update the README.md

Change the goal of this repository to: Improve portability and reusability by

- GUI layer separation
- NuGet package for the main compiler body
- Docker image generation for the CLI application
- ASP.NET GUI for the main compiler body

Consider creating the project description by merging the available documents created for the `ERASMUS`
